18/09/24 (10:43:18) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
18/09/24 (15:36:22) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
22/09/24 (11:48:06) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
24/09/24 (16:52:37) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
26/09/24 (21:13:03) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
09/10/24 (23:24:57) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
14/10/24 (15:13:54) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
17/10/24 (20:22:25) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
17/10/24 (20:22:40) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
20/10/24 (11:09:34) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
30/10/24 (08:27:44) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
03/11/24 (20:55:15) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
11/11/24 (22:28:06) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
26/12/24 (15:06:19) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
08/02/25 (18:13:28) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
20/02/25 (22:43:08) | ERROR: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/clix/.config/bpytop/themes'
